format = """\
    $directory\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $terraform\
    $aws\
    $kubernetes\
    $line_break\
    $character\
"""

[kubernetes]
format = '[$symbol$context( \($namespace\) )]($style)'
symbol = ""
style = "dimmed green"
disabled = false

[cmd_duration]
disabled = true

[aws]
format = 'on [$symbol($profile )(\($region\) )(\[$duration\])]($style)'
style = "blue"
symbol = ""

[terraform]
symbol = ""

[directory]
truncate_to_repo = false
