name: Lint and Format Lua

on:
  push:
  pull_request:

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Lua
        uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: "5.1"

      - name: Install luacheck
        run: luarocks install luacheck

      - name: Install stylua
        run: |
          curl -LO https://github.com/JohnnyMorganz/StyLua/releases/latest/download/stylua-linux-x86_64.zip
          unzip stylua-linux-x86_64.zip
          chmod +x stylua
          sudo mv stylua /usr/local/bin/
          rm stylua-linux-x86_64.zip

      - name: Run luacheck
        run: luacheck nvim/.

      - name: Run stylua (check mode)
        run: stylua --check nvim/.
